apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: istio-rollout-stable-service
  namespace: istio-verrazzano
spec:
  workload:
    apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: istio-rollout-vsvc
      namespace: istio-verrazzano
    spec:
      gateways:
      - istio-rollout-gateway
      hosts:
      - istio-rollout.apps.argoproj.io
      - istio-rollout.local
      http:
      - name: primary
        route:
        - destination:
            host: istio-rollout-stable
          weight: 100
        - destination:
            host: istio-rollout-canary
          weight: 0
